name: Update NanoNews
on:
  schedule:
    - cron: '0 */6 * * *' # Updates every 6 hours
  workflow_dispatch:      # Allows you to trigger it manually

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Fetch and Commit
        run: |
          pip install feedparser
          python fetch_news.py
          git config --global user.name "NanoBot"
          git config --global user.email "bot@nanonews.io"
          git add data.json
          git commit -m "Automated Nano Update" || exit 0
          git push
